# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e977da78e7dd9489e272bf1c15ee3179"
name = "RetainerPal Backend"
application_url = "https://example.com"
embedded = false

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,write_draft_orders,read_fulfillments,write_fulfillments,write_order_edits,read_order_edits,read_orders,write_orders,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
