# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d9493d0f3a77771606b2e34c7842b5d4"
name = "RetainerPal Backend"
application_url = "https://example.com"
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
